### PR TITLE
Add --validate option to vscode-tmgrammar-test

### LINKED ISSUE #26: Validation of grammars
@PanAeon could you give a CLI command to just validate grammars and see if they can load?

### PR DESCRIPTION
**Pull request by 4086606**
Closes #26. Untested, and can't handle grammar globs either.

### CODE REVIEW

**Comment by 4086606** [comment]
@PanAeon what about globs? Is there some native Node way to implement glob validation?

**Comment by PanAeon** [comment]
@4086606 I'm not sure what do you mean exactly by 'glob validation' ? Globs are needed only when searching for testcases, and there's a failsafe by default, that if no testcases are found the program will report an error.

BTW, I made a few tests, and it looks like currently `--validate` is only checking that grammar JSON is well formed and not regex patterns validity, which might be not what you expected it to do.

**Comment by 4086606** [comment]
I have a folder with five grammars and it would be useful to check them all in one test.

> `--validate` is only checking that grammar JSON is well formed and not regex patterns validity

Interesting. Maybe we can run it through a dummy testcase and force regex pattern validity check?

**Comment by PanAeon** [comment]
> I have a folder with five grammars and it would be useful to check them all in one test.
You can include multiple grammars by repeating `-g` options. Not sure that this is a popular use case so adding globe option might be a bit of extra work. 

 
> Interesting. Maybe we can run it through a dummy testcase and force regex pattern validity check?
Not sure... I think it's better to actually extract all regex patterns and compile them with oniguruma, but that's a bit of work

**Comment by 4086606** [comment]
> Not sure that this is a popular use case so adding globe option might be a bit of extra work.

Depends on the percentage of grammmars that are injection grammars.

**Comment by 4086606** [comment]
I found a solution - install [`foreach-cli`](https://www.npmjs.com/package/foreach-cli) and use that to glob the grammars subdirectory

**Comment by SNDST00M** [comment]
Any movement on the Oniguruma pattern validation? I've been need a tool that does this for awhile

**Comment by PanAeon** [comment]
@SNDST00M I suggest to write regular test cases or snapshots to validate the grammar, as the patterns could easily be syntactically valid, but do the wrong thing or combine badly with other patterns. 

We can reopen  #26 or create another issue if you still think there's a value in validating oniguruma patterns alone.

**Comment by SNDST00M** [comment]
I'll begin using the snapshot generator and if that isn't possible, I'll open a new issue

**Comment by SNDST00M** [comment]
It'd be best to document --validate as only checking well-formedness.
It promises pattern validity as well

**Pull request merged**
